name: Thorough C++ CI Integration Tests

on:
  push:
    branches: [ "main" ]

jobs:
  verify_thorough:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: jellyfish
      run: sudo apt install jellyfish
    - name: verify
      run: make verify
