name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_with_unittests:

    runs-on: ${{ matrix.os }}

    strategy:
      #matrix:
      #  os: [ubuntu-latest, macos-latest]
      matrix:
        os: [ ubuntu-latest ]
        compiler: [ latest, gcc-latest, gcc-9, gcc-10, g++-11, clang, clang-10, clang-11, clang++-12 ]
        include:
          - os: macos-latest
            compiler: gcc-latest
          - os: macos-latest
            compiler:  clang

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: submodule
      run: git submodule init; git submodule update
    - name: cpptests
      run: make cpptest

  verify_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: jellyfish
      run: sudo apt install jellyfish
    - name: verify
      run: make quick-verify
